name: Heroku Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'adopt'
      - uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Email that you use with heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # The appname to use for deploying/updating
          heroku_app_name: ${{secrets.HEROKU_APP}}
